### PR TITLE
Customizable validation message

### PR DESCRIPTION
**Pull request by ogidow**
This PR becomes validation message is customizable

example
```swift
row.add(rule: RuleRequired("customize message"))
```

### CODE REVIEW

**Comment by mtnbarreto** [comment]
code looks good! Thanks for contributing!

**Comment by Tibb** [comment]
Would love to use like this. Unfortunately, it doesn't seemed to work on my code:
capture d ecran 2017-02-09 a 10 24 30

As long as I try to put something else than the basic constructor `RuleRequired()`, I get this _Ruleset_ error.
What am I doing wrong?

**Comment by allenhuang** [comment]
@Tibb 
You need to code like this

`$0.add(rule: RuleRequired(msg:"My Error Message"))`

**Comment by Tibb** [comment]
Thanks @allenhuang , but this issue was actually related to missing imports in a previous version of the library. This is now fixed ;)

**Comment by allenhuang** [comment]
@Tibb 
hmmm, strange. I use the latest version (3.0.0) and still encounter the error you posted.

**Pull request merged**
