### PR TITLE
New PostalAddressRow for Eureka!

### LINKED ISSUE #104: "AddressRow" planned?
Is there anything like an "AddressRow" planned to build into Eureka?
I'm thinking of a row like in the iOS contact app, a row containing the following fields:

    [ Street       ]
    [ Suffix       ]
    [ Zip | City   ]
    [ Country      ]

### PR DESCRIPTION
**Pull request by marbetschar**
Fixes #104 - would love to see this in the official Eureka release!
Please see the following screenshot for what the row looks like:

simulator screen shot 09 01 2016 18 13 52

### CODE REVIEW

**Comment by ndmeiri** [comment]
+1!

**Comment by marbetschar** [comment]
@mtnbarreto any chance this gets merged in the official release?

**Comment by mtnbarreto** [comment]
@marbetschar Thanks for contributing! It's a great feature! 
Could you please amend your commits? I would prefer only one commit per feature. https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by marbetschar** [comment]
@mtnbarreto I've just rebased the branch. All changes are now present in one commit.

**Comment by marbetschar** [comment]
@mtnbarreto have I missed something to get this merged? Or maybe I've got just a lack of understanding how the merge / release process works on your end?

I know there are lots of things going on in regular working life and working on open source may not pay the bills. Therefore reacting instantly on requests and issues isn't always possible.

Even compared to other projects (mostly done by individuals) reaching out after a week or two seems fast at first sight.

On the other hand it drives me a bit sad to see theres currently not much love put into the community for Eureka here on GitHub. At least, this is the feeling I got while starring at the pull requests and issues.

As upon now, even if I look at myself, I'm not quite sure if I should put any more energy into Eureka as I cannot estimate if this energy would take Eureka to the next level - or simply puff out.

Don't get me wrong: This is complaining at high levels. I REALLY LOVE the work you guys have already put into this project and I'm very thankfull for it. Your ground work is the reason why I feel Eureka could become bigger & better quite fast. But I think it should take the next step in really engaging a community.

**Comment by mtnbarreto** [comment]
Hey @marbetschar,
My apologies for not being as responsive as you expected but i haven't had time to review the pull requests. Because of that I had to prioritize bugs and crashes over new features. This doesn't means the pull request won't get merged and/or reviewed. I will try to spend more time to get the pull requests merged.

I completely agree with you on that only the community can take Eureka to another level and really improve it. We have been merging almost all the eureka pull request so far as you can see int he project history. I love when anyone from the community contribute to eureka in any way as you did implementing PostalAddressRow.  

However some pull requests, feature proposals have a different direction than the direction we would like Eureka take and is hard to say this code is great it's useful but we will not merge it because is a very edge case scenario or it force everyone to have this framework dependency. We plan to have a repository or another project within the current repository to make these rows available to the community (as you already suggested in another issue). This is not the case if this particular pull request and we will merge it. 

Regarding this specific pull request (i'm not sure but) it seems to me that it is overridden other commits , take a look here:  https://github.com/xmartlabs/Eureka/commits/master and https://github.com/Mandelkind/Eureka/commits/feature-postaladdressrow.  As you can see SHA has changed for "Release 1.3.1" commit and this specific commit is the library [latest release tag](https://github.com/xmartlabs/Eureka/commit/bbae0ab29b955f95f4bd2057002dc58223f0c838).

As a general rule to contribute more efficiently, create one branch per pull request, try to have only one commit per feature using `git commit --amend`.  Use `git pull <xmartlabsEurekaRemote> <Remotebranch> --rebase` to put your commit/s on the top of the incomings remote changes. 

Could you please create a new pull request that doesn't change the current repository history? I recommend you to start from scratch copying pasting the feature code on top of latest repository commit.

Once again sorry for any delay in my responses. Please keep contributing to eureka!! I really appreciate your great work on it!

**Comment by marbetschar** [comment]
@mtnbarreto thank you very much for your detailed feedback. I really appreciate that!
To avoid any misunderstandings:

I tried *not* to point out, that you should invest more of your valuable time into pending pull requests like mine. Prioritizing bugs over new features is an absolute eligible and good decision. Yes, I can see you have merged almost every pull request into the official release and I really appreciate this too!!
Instead, what I've tried to point out is one question:

**How get a feeling of where Eureka goes?**

What's a bit missing for me now is a feeling of Eureka: How exactly do you see Eureka and where you want it to go? For what's the community striving? Maybe I have just missed some sort of discussion platform and this gap of education is entirely up to my end - but if I look at the issues page here on GitHub nearly all issues have zero comments, so this discussion seems to be inexistant. Does this discussion take place somewhere else?

Regarding the messed up branch: I'll starting from scratch, implementing the feature in a clean branch as soon as I get some spare time. This should be done by end of this week.

**Comment by marbetschar** [comment]
@mtnbarreto New, cleaned up pull request added: https://github.com/xmartlabs/Eureka/pull/187

**Comment by mtnbarreto** [comment]
@marbetschar thanks! 

In regards to "How get a feeling of where Eureka goes?" I will add a section to readme giving my thoughts about Eureka goals and how to contribute efficiently. 

Regarding the communication  channels, ideally we should use stackoverflow for general questions and help, this will give to maintainers more time to improve the library and to work on new features.

I will make it clear in the readme shortly.

**Comment by marbetschar** [comment]
Very cool!!!! Thank you! 👍🏼👍🏼

**Pull request closed without merging**
