### PR TITLE
Validations [WIP]

### PR DESCRIPTION
**Pull request by wouterw**
Attempt to resolve https://github.com/xmartlabs/Eureka/issues/47 and add some notion of validations to Eureka. I've take inspiration from XLForm.

I need this functionality for a project at work and will be exploring this further. It's very much a work in progress.

### CODE REVIEW

**Comment by michaelbina** [comment]
@wouterw Are you still working on this?  It looks promising and I'm thinking of integrating your branch since it hasn't been merged yet.

**Comment by wouterw** [comment]
@michaelbina I'm using this basic version in an app at work. It still lacks a few important pieces, such as some form of dirty tracking and validation state per row. If you have some time to work on this, feel free :+1:

**Comment by michaelbina** [comment]
Great.  Will let you know if I make any additions...

**Comment by txaidw** [comment]
Any news? Are you still working on this?

**Comment by txaidw** [comment]
👍

**Comment by entotsu** [comment]
👍

**Comment by mtnbarreto** [comment]
@wouterw  @michaelbina @txaiwieser @entotsu @jessedc  We have already implemented the validation feature, take a look at https://github.com/xmartlabs/Eureka#validations. Really appreciate if you can try out with it and give your feedback.

**Pull request closed without merging**
