### PR TITLE
Added new generic PickerInputRow similar to DateRow

### PR DESCRIPTION
**Pull request by migueliOS**
Hello, I added a missing type of row mentioned in one issue.
It's called PickerInputRow following all the styles and architecture you implemented.
It's been added a UI Test function to UITests for checking the picker changes the value properly.
Finally I added the Unit Tests Callbacks for this new control.

Regards!
Miguel.

### CODE REVIEW

**Comment by allaire** [comment]
Would be cool have this 👍

**Comment by sunbohong** [comment]
I also need this feature.

Can you rebase your commit?

If you can rebase it and this PR is merged to this repository,I can use it directly instead of rewrite myself.

**Comment by mats-claassen** [comment]
@geitoodevs have you plans of rebasing this? If not, we could do that as well.

**Comment by geitoodevs** [comment]
Sorry, I've been on vacation, I will check it as soon as possible. If you
want you can do it.


2016-08-29 21:28 GMT+02:00 Mathias Claassen <notifications@github.com>:

**Comment by maxwellahalife** [comment]
Any update on when we could expect this? I tried to go in and refactor it to Swift 3 myself but its a bit over my head.

**Comment by abdymm** [comment]
hai @migueliOS , how can i get value from these PickerInputRow ?

**Comment by mtnbarreto** [comment]
Hi @migueliOS ! thanks for contributing! After taking a look at Eureka rows seems this row was already implemented.

**Pull request closed without merging**
