### PR TITLE
SplitRow

### PR DESCRIPTION
**Pull request by marbetschar**
I'll created a new custom row called `SplitRow` which enables users to display two `Eureka` rows on the same line using the following signature:

```
form +++ Section()
	<<< SplitRow<PushRow<String>,TextRow>(){
		$0.rowLeft = PushRow<String>(){
			$0.selectorTitle = "E-Mail"
			$0.options = ["Private","Work","Others"]
		}
					
		$0.rowRight = TextRow(){
			$0.placeholder = "E-Mail"
		}
				
	}.onChange{
		print("SplitRow.onChange:","left:",$0.value?.left,"right:",$0.value?.right)
	}
```

Here's how it looks like:

splitrow

I'll happily submit the `SplitRow` to the `Eureka Community` but it needs this pull request to be merged into Eureka first to work properly.

### CODE REVIEW

**Comment by marbetschar** [comment]
As promised, `SplitRow` is now part of the `Eureka Community` project:

https://github.com/EurekaCommunity/SplitRow

**Comment by marbetschar** [comment]
I'd also love to add a Pull Request for the `PostalAddressRow`, which newly supports the country selection: https://github.com/Mandelkind/PostalAddressRow/tree/pushrow-country-selector

But we have to get this one merged first in order to get the updated `PostalAddressRow` working properly.

**Comment by mtnbarreto** [comment]
Hi @marbetschar. The row looks great!
I will close this pr since you already added the row to eureka community which is the proper place to provide these kind of features.

**Comment by marbetschar** [comment]
Missunderstanding here. `SplitRow` needs this change in `Eureka` in order to work properly:

https://github.com/xmartlabs/Eureka/pull/1338/commits/be4c01d20b1bcfcaf990baae092d75ff2bfe07b2

**Comment by marbetschar** [comment]
@mtnbarreto will this be merged too?

**Comment by liorp** [comment]
Is there any progress on commit [be4c01d](https://github.com/xmartlabs/Eureka/commit/be4c01d20b1bcfcaf990baae092d75ff2bfe07b2)?

**Comment by marbetschar** [comment]
@mtnbarreto will the[`var section` be `open`](https://github.com/xmartlabs/Eureka/commit/be4c01d20b1bcfcaf990baae092d75ff2bfe07b2) in a future Eureka release?

**Pull request closed without merging**
