### PR TITLE
Implemented the PhoneRow formatting function with PhoneNumberKit.

### PR DESCRIPTION
**Pull request by p-sun**
This is an alternative solution to #413 . #413 is light-weight but only formats numbers in the North American format, i.e. 1 (514) 234-2342.

I used SASDOE's suggestion to use PhoneNumberKit to automatically detect the device's region settings to format phone numbers accordingly. 

The PhoneNumberKit pod is included with this pull request, but if you prefer to run 'pod install' yourself, my relevant changes are located in:
- Podfile

In the Eureka target:
- Source/Rows/Common/FieldRow.swift
- Source/Rows/FieldRow.swift

In the Example target:
- ViewController.swift

### CODE REVIEW

**Comment by p-sun** [comment]
Interesting. Can anyone help me find out why this is failing the check on the FieldRowUITest, DecimalRowWithFormatterDuringInput? As far as I know, I hadn't modified DecimalRow...

**Comment by mats-claassen** [comment]
The error thrown by travis build is  
`/Users/travis/build/xmartlabs/Eureka/Source/Rows/Common/FieldRow.swift:10:8: no such module 'PhoneNumberKit'`.

**Comment by p-sun** [comment]
This build fails the check because I'm using the Pod PhoneNumberKit.
https://github.com/marmelroy/PhoneNumberKit

Pro: PhoneNumberKit allows for formatting that depends on the localization of the device. Allows for formatting as-you-type with Eureka's .onChange() function.
Con: Requires another CocoaPod.

For a lightweight PhoneRow formatting solution that doesn't depend on another Pod. Please see #413.

**Comment by mats-claassen** [comment]
Well this looks more like a custom row.
As it includes another pod we won't want to merge it here but it might be an useful addition. For example you could create a new pod repo in the [EurekaCommunity](https://github.com/EurekaCommunity) organisation. If you are interested we can add you there...

**Comment by p-sun** [comment]
Sure, I'd like to add it to the community.

**Comment by mats-claassen** [comment]
Ready. You should have received an invitation email

**Comment by p-sun** [comment]
Thank you.

**Comment by amadeu01** [comment]
@p-sun did you create a custom row for phone formatting?

**Pull request closed without merging**
