### PR TITLE
Add ZipCodeRow cell type

### PR DESCRIPTION
**Pull request by davidrothera**
As created for XLForm in https://github.com/xmartlabs/XLForm/commit/23b93a1a70bb17b8f2f65a4164978b6ac1190d9e this adds the ZipCode row type.

Example also added :+1:

### CODE REVIEW

**Comment by davidrothera** [comment]
Also, as a background to why this has been added, you need to change the keyboard and auto-capitilization properties of a textField however these settings are not observed in KVO :(

**Comment by mtnbarreto** [comment]
Hey @davidrothera, Thanks for contributing! 

I think that `ASCIICapable` keyboard type makes more sense than `.Default` for a zip code row because the `.Default` type allows to enter emoji icons. What do you think?

**Comment by smaspe** [comment]
@mtnbarreto How about `NamePhonePad` ? letters and numbers (bigger numbers). Punctuation is not use in zipcodes anywhere, afaik

**Comment by davidrothera** [comment]
The `.NamePhonePad` option doesn't support auto-capitilization so not really ideal here

**Pull request merged**
