### PR TITLE
Added SelectionListRow and SelectorInlineRow

### PR DESCRIPTION
**Pull request by loromits**
Hi!  
Just wrote two custom rows and found them pretty generic, so wanted to share with everybody:
### SelectionListRow
SelectionListRow
Row with tableView and optional header(if title is present).
Supports single selection, customizable textLabel text color and table insets
### SelectorInlineRow
SelectorInlineRow
Inline row based on SelectionListRow. Collapses on value picking.

### CODE REVIEW

**Comment by ilyapuchka** [comment]
Maybe https://github.com/EurekaCommunity will be a better place for that?

**Comment by cleg** [comment]
@ilyapuchka I think this is better to be merged in main repository, as this rows look more universal and generic then those in Community. IMHO they're better then inline picker row

**Comment by mtnbarreto** [comment]
Hey @loromits !! 
Thanks for contributing! I liked the rows! 
I think EurekaCommunity is the proper place to share these kind of rows. Do you have time to do so?

**Comment by loromits** [comment]
Hey, ok I don't mind moving it to Eureka Community

**Comment by mtnbarreto** [comment]
Hi @loromits I already gave you access to EurekaCommunity.  Looking forward to trying the new row types soon.

**Pull request closed without merging**
