### PR TITLE
Added cell setup callback in MultipleSelectorViewController

### PR DESCRIPTION
**Pull request by avalla**
I needed to change the value of title of the row in a MultipleSelectorViewController, but there was no way to do it.

So I addeed a new callback to do this.

Related issue #495

### CODE REVIEW

**Comment by mtnbarreto** [comment]
Hi @avalla  Why don't you use `selectableRowCellUpdate `?

**Comment by avalla** [comment]
I tried to use the update callback, but it is fired just after scrolling, the first time that the cell is displayed it wasn't fired.

it is not better to manipulate the title of the cell when during setup?

maybe i was using selectableRowCellUpdate it in the wrong way, this was my test:

```swift
let countries = [ "uk" : "United Kingdom", "fr" : "France", "us" : "United States"]
form +++ Section("Required fields".uppercaseString)
	<<< MultipleSelectorRow<String>("countries") { row in
	row.title = "Countries"
	row.options = countries.map { $0.0 }
	// Show the labels of selected values
	row.displayValueFor  = {
		if let t = $0 {
			return t.map({ countries[$0]! }).joinWithSeparator(", ")
		}
		return nil
	}
	row.onPresent({ from, to in
		// Add the label of the value on the right side of the cell after selection
		to.selectableRowCellUpdate = { cell, row in
			row.displayValueFor = { val in
				if let value = val {
					return countries[value]
				}
				return nil
			}
		}
	})
}
```

**Comment by mtnbarreto** [comment]
Yeah, the `displayValueFor ` should be changed before cell is displayed in the table view since this callback is used to update the cell text. 

As a workaround you can set up the textLabel.text from within the `selectableRowCellUpdate` as code below shows...

```swift
to.selectableRowCellUpdate = { cell, row in
            row.displayValueFor = { val in
                if let value = val {
                    return countries[value]
                }
                return nil
            }
            // don't remember exactly if we have to set up textLabel or detailTextLabel. 
            cell.textLabel.text = row.displayValueFor(row.value) // < ------------------------
        }
```

Anyway, the callback you added makes sense.
Thanks for contributing!

**Comment by avalla** [comment]
thanks to your for this useful library!! 👍

**Pull request merged**
