### PR TITLE
Update for Xcode 8 beta 5

### PR DESCRIPTION
**Pull request by jyunderwood**
This PR gets the swift3 branch running with tests passing under Xcode 8 beta 5 but seem to time out on travis.

One issue I ran in to is `canBecomeFirstResponder` is now a [read-only property](https://developer.apple.com/reference/uikit/uiresponder/1621130-canbecomefirstresponder
) instead of a method in the latest release. I have commented out the two overrides in the project with a TODO comment.

### CODE REVIEW

**Comment by mats-claassen** [comment]
Travis integration will probably always fail as Travis is currently using Xcode beta 4. 
Can we override `canBecomeFirstResponder` with a custom getter?

**Comment by jyunderwood** [comment]
@mats-claassen Yes, they they are now replaced with computed getter overrides.

**Comment by mtnbarreto** [comment]
👍

**Comment by mtnbarreto** [comment]
thanks for the great work @jyunderwood !

**Pull request merged**
