### PR TITLE
Adding support for SPM

### PR DESCRIPTION
**Pull request by thebluepotato**
Adds support for SPM, based on #1871 

CAUTION: the `Package.swift` file does not include a reference to `Eureka.bundle` because does not (yet) support ressources and assets (should change soon though AFAIK).

### CODE REVIEW

**Comment by thebluepotato** [comment]
Regarding #1808 : this PR contains the test target for Eureka as well and I'm not sur Accio will stay for too long now that SPM supports iOS and others.

**Comment by BalazsSzamody** [comment]
Hey, I found/created a solution for the bundle issue. For some reason I could't build it in the example project. Take a look at my branch: 
https://github.com/BalazsSzamody/Eureka/tree/SPM-Support

Let me know if I should make a PR.

**Comment by AndrewBennet** [comment]
Just a note to say that I've got another pull request (https://github.com/xmartlabs/Eureka/pull/1976) with a different solution: rather than jump through hoops to get a bundle working, the images in the bundle can be drawn in about 35 lines of code instead.

**Comment by mats-claassen** [comment]
This feature has been added in #1976

**Pull request closed without merging**
